language: cpp
 
git:
# Handle git submodules yourself
 submodules: false
before_install:
# Use sed to replace the SSH URL with the public URL, then initialize submodule 
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive
compiler:
 - gcc
install:
 - cd controllers
 - touch depend
 - gmake cpp_links
script:
 - cd controllers
 - gmake
 - gmake test
