language: cpp
compiler:
  - gcc
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install astyle=2.03-1 -qq
script:
 - pushd test && make test && popd
 - ./script/travis_format_checcker.sh
