# From:
# http://pblog.ebaker.me.uk/2014/01/uploading-arduino-sketch-from-raspberry.html


# Build commands:
# make
# make upload

# Note: BOARD_TAG and ARDUINO_PORT may change

ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM1
ARDUINO_LIBS =
include /usr/share/arduino/Arduino.mk
